'use client'

import { useMemo, useState } from 'react'
import { Search, SlidersHorizontal, ArrowUpDown, Star, Shield, Zap, Target, X, GitCompare, TrendingUp } from 'lucide-react'
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis } from 'recharts'

type Player = { id:number; name:string; club:string; league:string; country:string; position:string; age:number; overall:number; potential:number; pace:number; passing:number; shooting:number; defending:number; physical:number; value:number; wage:number; goals:number; assists:number; minutes:number }

const players: Player[] = [
 {id:1,name:'Jude Bellingham',club:'Real Madrid',league:'La Liga',country:'England',position:'CM',age:23,overall:91,potential:94,pace:82,passing:91,shooting:88,defending:78,physical:86,value:180,wage:320,goals:12,assists:9,minutes:2680},
 {id:2,name:'Pedri',club:'Barcelona',league:'La Liga',country:'Spain',position:'CM',age:23,overall:88,potential:92,pace:79,passing:94,shooting:76,defending:70,physical:66,value:140,wage:280,goals:7,assists:11,minutes:2410},
 {id:3,name:'Florian Wirtz',club:'Liverpool',league:'Premier League',country:'Germany',position:'AM',age:23,overall:89,potential:93,pace:84,passing:92,shooting:83,defending:52,physical:64,value:130,wage:240,goals:14,assists:12,minutes:2760},
 {id:4,name:'William Saliba',club:'Arsenal',league:'Premier League',country:'France',position:'CB',age:25,overall:89,potential:92,pace:86,passing:82,shooting:35,defending:94,physical:91,value:110,wage:210,goals:2,assists:1,minutes:2890},
 {id:5,name:'Lamine Yamal',club:'Barcelona',league:'La Liga',country:'Spain',position:'RW',age:19,overall:89,potential:97,pace:92,passing:91,shooting:84,defending:42,physical:61,value:210,wage:190,goals:18,assists:15,minutes:2920},
 {id:6,name:'João Neves',club:'PSG',league:'Ligue 1',country:'Portugal',position:'CM',age:21,overall:87,potential:94,pace:81,passing:90,shooting:61,defending:86,physical:75,value:105,wage:180,goals:5,assists:8,minutes:2640},
 {id:7,name:'Giorgio Scalvini',club:'Atalanta',league:'Serie A',country:'Italy',position:'CB',age:22,overall:82,potential:91,pace:76,passing:79,shooting:29,defending:84,physical:83,value:55,wage:80,goals:1,assists:2,minutes:2180},
 {id:8,name:'Benjamin Šeško',club:'Man United',league:'Premier League',country:'Slovenia',position:'ST',age:23,overall:85,potential:93,pace:89,passing:68,shooting:90,defending:35,physical:88,value:95,wage:170,goals:19,assists:5,minutes:2510},
 {id:9,name:'Bukayo Saka',club:'Arsenal',league:'Premier League',country:'England',position:'RW',age:25,overall:90,potential:93,pace:89,passing:88,shooting:87,defending:51,physical:73,value:155,wage:290,goals:17,assists:13,minutes:3010},
 {id:10,name:'Pau Cubarsí',club:'Barcelona',league:'La Liga',country:'Spain',position:'CB',age:19,overall:83,potential:95,pace:77,passing:86,shooting:25,defending:87,physical:70,value:75,wage:90,goals:1,assists:3,minutes:2330},
 {id:11,name:'Endrick',club:'Real Madrid',league:'La Liga',country:'Brazil',position:'ST',age:20,overall:80,potential:94,pace:91,passing:62,shooting:86,defending:30,physical:82,value:80,wage:110,goals:13,assists:4,minutes:1740},
 {id:12,name:'Michael Olise',club:'Bayern Munich',league:'Bundesliga',country:'France',position:'RW',age:24,overall:87,potential:91,pace:86,passing:90,shooting:82,defending:39,physical:67,value:100,wage:190,goals:15,assists:14,minutes:2780},
 {id:13,name:'Kenan Yıldız',club:'Juventus',league:'Serie A',country:'Turkey',position:'LW',age:21,overall:81,potential:92,pace:87,passing:78,shooting:79,defending:36,physical:68,value:60,wage:75,goals:10,assists:8,minutes:2210},
 {id:14,name:'Arda Güler',club:'Real Madrid',league:'La Liga',country:'Turkey',position:'AM',age:21,overall:82,potential:93,pace:79,passing:91,shooting:84,defending:31,physical:58,value:65,wage:95,goals:9,assists:10,minutes:1930},
 {id:15,name:'Warren Zaïre-Emery',club:'PSG',league:'Ligue 1',country:'France',position:'CM',age:20,overall:84,potential:93,pace:78,passing:86,shooting:68,defending:81,physical:79,value:90,wage:125,goals:6,assists:7,minutes:2550},
 {id:16,name:'Milos Kerkez',club:'Liverpool',league:'Premier League',country:'Hungary',position:'LB',age:22,overall:82,potential:89,pace:91,passing:76,shooting:42,defending:79,physical:82,value:58,wage:90,goals:3,assists:7,minutes:2460},
 {id:17,name:'Alejandro Garnacho',club:'Chelsea',league:'Premier League',country:'Argentina',position:'LW',age:22,overall:84,potential:91,pace:94,passing:78,shooting:81,defending:39,physical:65,value:88,wage:150,goals:14,assists:9,minutes:2490},
 {id:18,name:'Dean Huijsen',club:'Real Madrid',league:'La Liga',country:'Spain',position:'CB',age:21,overall:81,potential:92,pace:82,passing:88,shooting:34,defending:83,physical:85,value:62,wage:85,goals:2,assists:2,minutes:2380},
 {id:19,name:'Désiré Doué',club:'PSG',league:'Ligue 1',country:'France',position:'AM',age:21,overall:83,potential:94,pace:90,passing:84,shooting:80,defending:33,physical:71,value:92,wage:120,goals:12,assists:11,minutes:2260},
 {id:20,name:'Franco Mastantuono',club:'Real Madrid',league:'La Liga',country:'Argentina',position:'AM',age:18,overall:78,potential:93,pace:84,passing:87,shooting:72,defending:28,physical:55,value:55,wage:60,goals:8,assists:12,minutes:2010}
]

const radar = (p:Player) => [{subject:'Pace',A:p.pace},{subject:'Passing',A:p.passing},{subject:'Shooting',A:p.shooting},{subject:'Defending',A:p.defending},{subject:'Physical',A:p.physical}]
const scoutingScore = (p:Player) => Math.round(p.potential*.45 + p.overall*.3 + Math.min(p.minutes/30,100)*.1 + Math.min((p.goals+p.assists)*2,100)*.1 + Math.max(0,100-p.value/2)*.05)

type SortKey = 'score' | 'overall' | 'potential' | 'value'
const sortValue = (p:Player, key:SortKey) => key === 'score' ? scoutingScore(p) : p[key]

export default function Home(){
 const [query,setQuery]=useState(''); const [position,setPosition]=useState('All'); const [league,setLeague]=useState('All'); const [minPotential,setMinPotential]=useState(0); const [selected,setSelected]=useState(players[0]); const [compare,setCompare]=useState<Player|null>(null); const [shortlist,setShortlist]=useState<number[]>([1,5]); const [sort,setSort]=useState<SortKey>('score'); const [advanced,setAdvanced]=useState(false)
 const filtered=useMemo(()=>players.filter(p=>(p.name+' '+p.club+' '+p.country).toLowerCase().includes(query.toLowerCase())&&(position==='All'||p.position===position)&&(league==='All'||p.league===league)&&p.potential>=minPotential).sort((a,b)=>sortValue(b,sort)-sortValue(a,sort)),[query,position,league,minPotential,sort])
 const score=scoutingScore(selected)
 const toggleShortlist=(id:number)=>setShortlist(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
 return <main>
  <header className="topbar"><div className="brand"><div className="logo">S</div><div><b>SCOUT<span>IQ</span></b><small>FOOTBALL INTELLIGENCE</small></div></div><div className="status"><i/> DATABASE ONLINE <span>•</span> 8,412 PLAYERS</div></header>
  <section className="hero"><div><p className="eyebrow">SCOUTING COMMAND CENTER · DAY 01</p><h1>Find the next <span>superstar.</span></h1><p className="sub">Data-driven recruitment. Screen talent, calculate a scouting score, compare profiles and build a shortlist before the market catches up.</p></div><div className="heroStats"><div><strong>8,412</strong><span>PLAYERS</span></div><div><strong>47</strong><span>LEAGUES</span></div><div><strong>{shortlist.length}</strong><span>SHORTLISTED</span></div></div></section>
  <section className="workspace">
   <div className="controls"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search player, club or country..."/></div><select value={position} onChange={e=>setPosition(e.target.value)}><option>All</option>{['GK','CB','LB','RB','CM','AM','LW','RW','ST'].map(x=><option key={x}>{x}</option>)}</select><select value={league} onChange={e=>setLeague(e.target.value)}><option>All</option>{['Premier League','La Liga','Serie A','Bundesliga','Ligue 1'].map(x=><option key={x}>{x}</option>)}</select><label className="range">MIN POTENTIAL <input type="range" min="0" max="97" value={minPotential} onChange={e=>setMinPotential(+e.target.value)}/><b>{minPotential || 'ANY'}</b></label><button className={'ghost '+(advanced?'activeBtn':'')} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/> ADVANCED</button></div>
   {advanced&&<div className="advanced"><span>MODEL: <b>SCOUTIQ V1</b></span><span>SCORING: <b>Potential 45% · Overall 30% · Form 20% · Value 5%</b></span><span>RESULTS: <b>{filtered.length}</b></span></div>}
   <div className="grid"><div className="panel listPanel"><div className="panelHead"><div><h2>PLAYER DATABASE</h2><p>{filtered.length} prospects match your criteria</p></div><button className="sort" onClick={()=>setSort(sort==='score'?'overall':sort==='overall'?'potential':sort==='potential'?'value':'score')}><ArrowUpDown size={14}/> SORT: {sort.toUpperCase()}</button></div><div className="tableHead"><span>PLAYER</span><span>POS</span><span>AGE</span><span>OVR</span><span>POT</span><span>VALUE</span><span>SCORE</span></div>{filtered.map(p=><button className={'playerRow '+(selected.id===p.id?'active':'')} key={p.id} onClick={()=>setSelected(p)}><span className="player"><span className="avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span><b>{p.name}</b><small>{p.club} · {p.country}</small></span></span><span>{p.position}</span><span>{p.age}</span><strong>{p.overall}</strong><strong className="potential">{p.potential}</strong><span>€{p.value}M</span><span className="fit">{scoutingScore(p)}</span></button>)}</div>
   <aside className="panel detail"><div className="detailTop"><span className="tag">{shortlist.includes(selected.id)?'SHORTLISTED':'SCOUTED'}</span><span className="fitBadge">{score}/100 SCORE</span></div><div className="profile"><div className="bigAvatar">{selected.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h2>{selected.name}</h2><p>{selected.club} · {selected.league} · {selected.position} · Age {selected.age}</p></div></div><div className="ratings"><div><small>OVERALL</small><b>{selected.overall}</b></div><div><small>POTENTIAL</small><b>{selected.potential}</b></div><div><small>MARKET VALUE</small><b>€{selected.value}M</b></div></div><div className="chart"><ResponsiveContainer width="100%" height={240}><RadarChart data={radar(selected)}><PolarGrid/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:'#77818d'}}/><Radar dataKey="A" strokeWidth={2} fillOpacity={0.18}/><Tooltip/></RadarChart></ResponsiveContainer></div><div className="insights"><h3>SCOUTING INSIGHTS</h3><p><TrendingUp size={15}/> <b>Upside</b> — {selected.potential-selected.overall} OVR points of projected growth.</p><p><Zap size={15}/> <b>Production</b> — {selected.goals} goals + {selected.assists} assists in {selected.minutes.toLocaleString()} minutes.</p><p><Target size={15}/> <b>Value signal</b> — €{Math.round(selected.value/(selected.overall+selected.potential)*100)}M per combined rating point.</p><p><Shield size={15}/> <b>Role fit</b> — profile suits a modern {selected.position} in a possession-heavy system.</p></div><div className="actions"><button className="shortlist" onClick={()=>toggleShortlist(selected.id)}><Star size={16} fill={shortlist.includes(selected.id)?'currentColor':'none'}/> {shortlist.includes(selected.id)?'REMOVE FROM SHORTLIST':'ADD TO SHORTLIST'}</button><button className="compareBtn" onClick={()=>setCompare(compare?.id===selected.id?null:selected)}><GitCompare size={16}/> {compare?.id===selected.id?'COMPARING':'COMPARE'}</button></div></aside></div>
   {compare&&<section className="panel comparePanel"><div className="panelHead"><div><h2>PLAYER COMPARISON</h2><p>{selected.name} vs {compare.name}</p></div><button className="close" onClick={()=>setCompare(null)}><X size={18}/></button></div><div className="compareGrid">{[selected,compare].map(p=><div className="compareCard" key={p.id}><div className="compareName"><span className="avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{p.name}</b><small>{p.club} · {p.position}</small></div><strong>{scoutingScore(p)}</strong></div>{[['Overall',p.overall],['Potential',p.potential],['Pace',p.pace],['Passing',p.passing],['Shooting',p.shooting],['Defending',p.defending],['Physical',p.physical]].map(([label,val])=><div className="metric" key={String(label)}><span>{label}</span><div><i style={{width:`${Number(val)}%`}}/></div><b>{val}</b></div>)}</div>)}</div></section>}
   <section className="bottomGrid"><div className="panel"><div className="panelHead"><div><h2>SCOUTING PIPELINE</h2><p>Recommended targets by position</p></div></div><div className="pipeline">{['ST','AM','CM','CB','RW'].map(pos=>{const best=players.filter(p=>p.position===pos).sort((a,b)=>scoutingScore(b)-scoutingScore(a))[0]; return <button key={pos} onClick={()=>best&&setSelected(best)}><span>{pos}</span><b>{best?.name||'No profile'}</b><small>{best?`${scoutingScore(best)} score · €${best.value}M`:''}</small></button>})}</div></div><div className="panel chartPanel"><div className="panelHead"><div><h2>MARKET SNAPSHOT</h2><p>Average potential by league</p></div></div><ResponsiveContainer width="100%" height={190}><BarChart data={['Premier League','La Liga','Serie A','Bundesliga','Ligue 1'].map(l=>({league:l.replace('Premier League','EPL'),potential:Math.round(players.filter(p=>p.league===l).reduce((a,p)=>a+p.potential,0)/Math.max(1,players.filter(p=>p.league===l).length))}))}><XAxis dataKey="league" tick={{fontSize:9}}/><YAxis domain={[75,100]} tick={{fontSize:9}}/><Tooltip/><Bar dataKey="potential" fill="currentColor"/></BarChart></ResponsiveContainer></div></section>
  </section><footer>SCOUTIQ · FOOTBALL SCOUTING ANALYTICS <span>DATA-DRIVEN RECRUITMENT PLATFORM · V1</span></footer>
 </main>
}